config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  
  devise_for :users, skip: :registrations
  devise_for :visitors, skip: [:sessions]

  root to: 'pages#index'

  resources :looks
  scope :looks do 
  	resources :categories, only: :show, as: :by_category
  end
  resources :influencers
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
	has_many :looks
	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                      :integer          not null, primary key
#  type                    :string(255)
#  attachment_file_name    :string(255)
#  attachment_content_type :string(255)
#  attachment_file_size    :integer
#  attachment_updated_at   :datetime
#  imageable_id            :integer
#  imageable_type          :string(255)
#  created_at              :datetime
#  updated_at              :datetime
#

class Image < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true
	delegate :url, to: :attachment
end

app/models/influencer.rb
# == Schema Information
#
# Table name: influencers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Influencer < ActiveRecord::Base
	has_many :looks
	has_one :headshot, as: :imageable

	after_create :ensure_headshot

	accepts_nested_attributes_for :headshot

	def self.alphabetize
		all.sort_by{ |i| i.name }.group_by{|i| i.name.first }
	end

	private

	def ensure_headshot
		self.headshot || self.create_headshot
	end
end

app/models/influencer/headshot.rb
# == Schema Information
#
# Table name: images
#
#  id                      :integer          not null, primary key
#  type                    :string(255)
#  attachment_file_name    :string(255)
#  attachment_content_type :string(255)
#  attachment_file_size    :integer
#  attachment_updated_at   :datetime
#  imageable_id            :integer
#  imageable_type          :string(255)
#  created_at              :datetime
#  updated_at              :datetime
#

class Influencer::Headshot < Image
	has_attached_file :attachment, styles: {small: "153x180", thumb: "100x100"}, default_url: 'headshot/:style/missing.png'
	validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/look.rb
# == Schema Information
#
# Table name: looks
#
#  id            :integer          not null, primary key
#  title         :string(255)
#  slug          :string(255)
#  body          :text
#  influencer_id :integer          not null
#  category_id   :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Look < ActiveRecord::Base
	belongs_to :influencer
	has_one :primary_image, as: :imageable, class_name: "Look::PrimaryImage"
	has_many :product_groups
	belongs_to :category

	extend FriendlyId

	friendly_id :title, use: [:slugged, :finders]

	after_create :ensure_primary_image

	accepts_nested_attributes_for :primary_image, :product_groups

	validates :influencer, :title, :body, :category, presence: true

	def primary_product_group
		product_groups.first
	end

	def secondary_product_groups
		groups = product_groups.to_a
		groups.size == 1 ? [] : groups.slice(1 .. -1)
	end

	private

	def ensure_primary_image
		self.primary_image || self.create_primary_image
	end
end

app/models/look/primary_image.rb
# == Schema Information
#
# Table name: images
#
#  id                      :integer          not null, primary key
#  type                    :string(255)
#  attachment_file_name    :string(255)
#  attachment_content_type :string(255)
#  attachment_file_size    :integer
#  attachment_updated_at   :datetime
#  imageable_id            :integer
#  imageable_type          :string(255)
#  created_at              :datetime
#  updated_at              :datetime
#

class Look::PrimaryImage < Image
	has_attached_file :attachment, styles: {large: "331x518", thumb: '100x100'}, default_url: 'look_image/:style/missing.png'
	validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  brand       :string(255)
#  model       :string(255)
#  price_cents :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Product < ActiveRecord::Base
	has_one :image, as: :imageable, class_name: "Product::Image"
	after_create :ensure_image

	private 

	def ensure_image
		self.image || self.create_image
	end
end

app/models/product/image.rb
# == Schema Information
#
# Table name: images
#
#  id                      :integer          not null, primary key
#  type                    :string(255)
#  attachment_file_name    :string(255)
#  attachment_content_type :string(255)
#  attachment_file_size    :integer
#  attachment_updated_at   :datetime
#  imageable_id            :integer
#  imageable_type          :string(255)
#  created_at              :datetime
#  updated_at              :datetime
#

class Product::Image < Image
	has_attached_file :attachment, styles: {large: "331x518", medium: "186x186>", small: "120x120>", thumb: "100x100"}, default_url: 'product_image/:style/missing.png'
	validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/product_group.rb
# == Schema Information
#
# Table name: product_groups
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  look_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class ProductGroup < ActiveRecord::Base
	belongs_to :look
	has_many :items, class_name: "ProductGroup::Item", foreign_key: :group_id
	has_many :products, through: :items

	accepts_nested_attributes_for :items
end

app/models/product_group/item.rb
# == Schema Information
#
# Table name: product_group_items
#
#  id         :integer          not null, primary key
#  group_id   :integer
#  product_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class ProductGroup::Item < ActiveRecord::Base
	belongs_to :product
	belongs_to :product_group
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user/visitor.rb
class Visitor < User

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		load_looks
	end

	private
	def load_category
		@category ||= Category.find(params[:id])
	end

	def load_looks
		@looks ||= load_category.looks
	end
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController
	def index 
		load_influencers
	end

	def show
		load_influencer
	end

	private

	def load_influencers
		@influencers ||= influencer_scope.includes(:headshot).alphabetize
	end

	def load_influencer
		@influencer ||= influencer_scope.includes(:looks).find(params[:id])
	end

	def influencer_scope
		Influencer.all
	end
end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
	def index
		load_looks
	end

	def show
		load_look
	end

	private

	def load_look
		@look = looks_scope.includes(:primary_image, product_groups: {products: :image}).find(params[:id])
	end

	def load_looks
		@looks = looks_scope.to_a
	end

	def looks_scope
		Look.all
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/form_helper.rb
module FormHelper

end

app/helpers/looks_helper.rb
module LooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/show.html.haml
%h2=@category.title
%ul
	-@looks.each do |l|
		%li= l.title

app/views/influencers/_abc_influencer.html.haml
%li
	=link_to influencer_path(i) do 
		=image_tag i.headshot.url(:small) if i.headshot
	%p=i.name

app/views/influencers/index.html.haml
.influencers.row
	-letters = "A".."Z"
	
	%ul.letter-anchors
		-letters.each do |l|
			%li
				%a(href="#" data-letter="letter-#{l}")= l
	
	-letters.each do |letter|
		%section.letter(id="letter-#{letter}")
			%h1=letter
			%a.to-top ^
			%ul
				-if @influencers.has_key?(letter)
					=render partial: 'abc_influencer', collection: @influencers[letter], as: :i
						

app/views/influencers/show.html.haml
=@influencer.name

%ul.looks
	-@influencer.looks.each do |l|
		%li.look
			=link_to look_path(l) do 
				=placeholdit "210x400"
			%p=l.title

app/views/looks/index.html.haml
%ul
	-@looks.each do |l|
		%li
			=link_to look_path(l) do
				=placeholdit "210x400"
			%h3=l.title
			%p=l.body

app/views/looks/show.html.haml
.row
	.four.columns.alpha
		=image_tag @look.primary_image.url(:large)
	.eight.columns.omega
		.row
			%h2=@look.title
			=@look.body
		-@look.primary_product_group.tap do |g|
			.primary_group.product_group
				=g.name
				%ul.products
					-g.products.each do |p|
						%li
							=image_tag p.image.url(:medium)
							%p=p.brand
							%p=p.model
							%p=p.price_cents
-@look.secondary_product_groups.each do |g|
	.row.product_group
		=g.name
		%ul.products
			-g.products.each do |p|
				%li
					=image_tag p.image.url(:medium)
					%p=p.brand
					%p=p.model
					%p=p.price_cents

:javascript
	$(function(){
		var group = $('.primary_group ul.products');
		if(group.find('li').length > 3) {
			$('.primary_group ul.products').slick({
				slide: "li",
				infinite: true,
				slidesToShow: 3,
				slidesToScroll: 1
			});
		}
	});
	

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>